name: MakeCode Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install MakeCode Tools
      run: npm install -g makecode

    - name: Build Blocks
      run: makecode
